### ISSUE TITLE
Tests won't run unless Coffee-Script is a dependency of the root project

### ISSUE THREAD

**Issue by thompsnm** [ReadyTalk/cukefarm#2]
When trying to run tests using CukeFarm without including CoffeeScript as a dependency of the root project errors such as the following are thrown:
```
config.cucumberOpts.require.push req for req in ['../support/World.coffee', '.
                                 ^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    [...]
```
The workaround for this is to add CoffeeScript as a dependency to your project by running the following command:
```
npm install --save-dev coffee-script
```
A potential fix for this issue is adding a prepublish step that will compile all files to Javascript before publishing to npm.

**Comment by dansomething** [comment]
Why can't coffee-script just be added to the package.json and committed?

**Comment by thompsnm** [comment]
Coffee-script actually is in the package.json as a dependency already, so I'm not sure why this is happening. More investigation is warranted.

Interestingly, I also tried installing coffee-script globally and I hit this same issue. For some reason the only way to avoid this that I know of is to install coffee-script on the on your own project.

**Comment by watsoncj** [comment]
The error posted in the description appears to use CoffeeScript in the root project without using the CS interpreter. At least that's my assumption since the only place in CukeFarm that I could find `push req for req in […]` was in `README.MD`.

I second the option of putting the compiled JavaScript main file in the published npm artifact.

It seems that most libraries intended for general use expose JavaScript for inclusion since it fits into any build without requiring a specific interpreter like CoffeeScript, TypeScript, etc.

This approach looks promising:
http://stackoverflow.com/questions/26196595/how-do-i-compile-coffeescript-before-publishing-to-npm

Heavier handed approach with Makefile:
http://stackoverflow.com/questions/13645824/can-i-write-npm-package-in-coffeescript

**Comment by dansomething** [comment]
Or configure grunt-contrib-coffee in the existing Gruntfile. Either way I agree. It's more typical to see JS shipped and more universal.

**Comment by thompsnm** [comment]
I like the idea of using the light approach that @watsoncj proposed. If we need to use the JS file for other Grunt tasks in the future I would be a fan of pulling in grunt-contrib-coffee then. For now though we can have a little less overhead by calling CS directly from an npm script. I'll try to implement the prepublish script shortly.
