### ISSUE TITLE
How to use multiple locator elements in a single step def?

### ISSUE THREAD

**Issue by uv01** [ReadyTalk/cukefarm#49]
Hi @thompsnm ,

Thank you for such an amazing project. This has been really useful for us. 
I am trying to pass multiple locators from the same page object to a step definition. Please check the example below :

```When('I verify in the "{elementName}"{elementType} table that catagory label "{elementName}"{elementType} should have value "{captureString}"',{timeout : 120*1000},

 function (rowRepeater,type,columnValue, type1,sortString) {
        var rowElem = rowRepeater + type;
        var columnElem = columnValue + type1;    
        return this.currentPage[rowElem].filter(function(elem){
            return elem.this.currentPage[columnElem].getText().then(function(name){
                //return the row which has your value (textproxy)
                return expect(name).to.include(sortString);
            });
        });
    });
```

This gives below error : 
TypeError: Cannot read property 'currentPage' of undefined

However, when i replace **this.currentPage[columnElem]** with the locator such as (element(by.css("...") , it works fine.

```When('I verify in the "{elementName}"{elementType} table that catagory label "{elementName}"{elementType} should have value "{captureString}"',{timeout : 120*1000},

 function (rowRepeater,type,columnValue, type1,sortString) {
        var rowElem = rowRepeater + type;
        var columnElem = columnValue + type1;  
        return this.currentPage[rowElem].filter(function(elem){
            return elem.element(by.css("...").getText().then(function(name){
                //return the row which has your value (textproxy)
                return expect(name).to.include(sortString);
            });
        });
     });
```

Could you please let me know how to use multiple locator in a step def ?

**Comment by uv01** [comment]
@thompsnm : could you please be able to look into this.

**Comment by thompsnm** [comment]
Hey @uv01 ,

Sorry for the delay. You've probably figured out your error by now, but I'll leave an answer in case anyone else comes here with a similar issue. In the context of a Cucumber test `this` refers to the World object, and since you have initialized the World with a `currentPage` property you are able to access elements on the current page using `this.currentPage[someElement]`.

In your failing example however, you are not trying to access properties on the World. You have appended `this.currentPage[someElement]` onto a Protractor Element object. In doing so, you are now looking for a property called `this` on the element, which doesn't exist, hence the error that you are then trying to read properties from `undefined`. If you want to locate child elements in Protractor you _have_ to do something like the second example in which you call the `element()` function on the element that was found by the `filter()` function. Since you don't want to hard code the locator into the test though, I would recommend using the [`locator()` function that Protractor exposes on all element objects](http://www.protractortest.org/#/api?view=ElementArrayFinder.prototype.locator) to access the locator you used to define the `columnElem` on the page object. Your final code would then look something like this:

    function (rowRepeater,type,columnValue, type1,sortString) {
        var rowElem = rowRepeater + type;
        var columnElem = columnValue + type1;  
        return this.currentPage[rowElem].filter(function(elem){
            return elem.element(this.currentPage[columnElem].locator()).getText().then(function(name){
                //return the row which has your value (textproxy)
                return expect(name).to.include(sortString);
            });
        });
     });
